    \begin{finalframe}
      \begin{itemize}
      \item Dieses Handout steht unter der Lizenz CC BY 3.0 DE.

      Details hierzu finden Sie unter
      \url{https://creativecommons.org/licenses/by/3.0/deed.de}.

      \item Diese Datei wurde erstellt am: \DTMnow

      Die jeweils neueste Version
      finden Sie hier im Ordner \enquote{Theoretische Elektrotechnik}: \url{https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/27455913992/CourseNode/103138906469436}

      \item Wenn Sie einen Fehler entdecken, freue ich mich über einen kurzen
        Hinweis an \url{mailto:tetemv@tu-dresden.de}!
        \item Das Video zu dieser Lerneinheit (und zu weiteren) finden
          Sie entweder auf dem Videocampus Sachsen (\url{https://videocampus.sachsen.de/album/view/aid/287}) oder auf YouTube (\url{https://www.youtube.com/channel/UCDWsIsdJSggNXdYc9d1k65Q}).
      \end{itemize}
      \end{finalframe}
