name: latexmk
on:
  push:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: yegor256/latexmk-action@0.8.0
        with:
          cmd: latexmk
          path: build
          opts: -pdf
          packages: beamer tikz
